"""Phase 7: FastAPI interface over the Phase 5 agent. Four endpoints per
SPEC.md - GET /health, GET /patients, GET /patients/{id}/card,
POST /patients/{id}/card/refresh. OpenAPI docs are auto-generated by
FastAPI at /docs.

Card caching is deliberately simple: an in-process dict, not a database
table. GET returns a cached card if one exists (generating it on first
request), POST /refresh always regenerates and replaces the cache entry.
This is a demo-scope choice, not a production one - a real deployment
would persist cards with a TTL/invalidation policy, which is out of scope
for what this phase needs to demonstrate. The cache is lost on restart,
which is fine: nothing here is PHI (synthetic data only, see
docs/SAFETY_AND_PRIVACY.md) and every card is trivially regenerable.
"""

from contextlib import asynccontextmanager
from typing import Any

from fastapi import Depends, FastAPI, HTTPException, Request
from pydantic import BaseModel
from sqlalchemy import text
from sqlalchemy.engine import Engine

from previsit.agent.graph import generate_previsit_card
from previsit.config import settings
from previsit.ingest.loader import get_engine
from previsit.models import PreVisitCard


@asynccontextmanager
async def lifespan(app: FastAPI):
    app.state.engine = get_engine()
    app.state.card_cache = {}
    try:
        yield
    finally:
        app.state.engine.dispose()


app = FastAPI(
    title="Pre-Visit Clinical Intelligence Agent",
    description=(
        "Generates a citation-backed pre-visit summary card for a synthetic patient. "
        "Every claim on a card traces back to a specific FHIR-derived record - see the "
        "source_resource_ids on each finding. 100% synthetic Synthea data; see "
        "docs/SAFETY_AND_PRIVACY.md."
    ),
    version="0.1.0",
    lifespan=lifespan,
)


def get_db_engine(request: Request) -> Engine:
    return request.app.state.engine


def _patient_exists(engine: Engine, patient_id: str) -> bool:
    with engine.connect() as conn:
        row = conn.execute(text("SELECT 1 FROM dim_patient WHERE patient_id = :pid"), {"pid": patient_id}).fetchone()
    return row is not None


def _generate_card(engine: Engine, patient_id: str) -> PreVisitCard:
    if not _patient_exists(engine, patient_id):
        raise HTTPException(status_code=404, detail=f"Unknown patient_id: {patient_id}")
    try:
        return generate_previsit_card(engine, patient_id)
    except Exception as exc:  # noqa: BLE001 - an upstream LLM/provider failure must not leak as a raw 500
        raise HTTPException(status_code=502, detail=f"Card generation failed: {type(exc).__name__}: {exc}") from exc


class PatientListItem(BaseModel):
    patient_id: str
    birth_date: str | None
    gender: str | None
    deceased_flag: bool
    city: str | None
    state: str | None


@app.get("/health")
def health() -> dict[str, str]:
    return {"status": "ok"}


@app.get("/patients", response_model=list[PatientListItem])
def list_patients(
    limit: int = 50,
    offset: int = 0,
    engine: Engine = Depends(get_db_engine),
) -> list[dict[str, Any]]:
    if not (1 <= limit <= 500):
        raise HTTPException(status_code=422, detail="limit must be between 1 and 500")
    with engine.connect() as conn:
        rows = conn.execute(
            text(
                "SELECT patient_id, birth_date, gender, deceased_flag, city, state "
                "FROM dim_patient ORDER BY patient_id OFFSET :offset ROWS FETCH NEXT :limit ROWS ONLY"
            ),
            {"offset": offset, "limit": limit},
        ).mappings().all()
    return [
        {
            "patient_id": r["patient_id"],
            "birth_date": r["birth_date"].isoformat() if r["birth_date"] else None,
            "gender": r["gender"],
            "deceased_flag": bool(r["deceased_flag"]),
            "city": r["city"],
            "state": r["state"],
        }
        for r in rows
    ]


@app.get("/patients/{patient_id}/card", response_model=PreVisitCard)
def get_card(patient_id: str, request: Request, engine: Engine = Depends(get_db_engine)) -> PreVisitCard:
    cache: dict[str, PreVisitCard] = request.app.state.card_cache
    if patient_id not in cache:
        cache[patient_id] = _generate_card(engine, patient_id)
    return cache[patient_id]


@app.post("/patients/{patient_id}/card/refresh", response_model=PreVisitCard)
def refresh_card(patient_id: str, request: Request, engine: Engine = Depends(get_db_engine)) -> PreVisitCard:
    card = _generate_card(engine, patient_id)
    request.app.state.card_cache[patient_id] = card
    return card


if __name__ == "__main__":
    import uvicorn

    uvicorn.run("previsit.api.main:app", host=settings.api_host, port=settings.api_port, reload=True)
